language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/


before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

install:
  - mvn clean install

script:
  - cat target/test-results/index.html

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
